import type {NextPage} from "next";
import Head from "next/head";
import Header from "../Components/UI/Header/Header";
import DeckBuilder from "../Components/DeckBuilder/DeckBuilder";
import {prisma} from "../db/client";
import {RuneterraCard} from "../Components/DeckBuilder/types";
import {CardContext} from "../Components/Contexts/CardContext";
import RiotDisclosure from "../Components/RiotDisclosure/RiotDisclosure";

export async function getStaticProps() {
    const res = await prisma.cards.findMany({
        where: {
            card: {
                path: "$.collectible",
                equals: true,
            },
        },
    });

    const cards = res
        .sort(({card: cardA}, {card: cardB}) => {
            const {cost: costA} = cardA as unknown as RuneterraCard;
            const {cost: costB} = cardB as unknown as RuneterraCard;
            const {rarity: rarityA} = cardA as unknown as RuneterraCard;
            const {rarity: rarityB} = cardB as unknown as RuneterraCard;
            if (rarityA !== rarityB) {
                if (rarityA === "Champion") return -1;
                if (rarityB === "Champion") return 1;
            }
            return costA - costB;
        })
        .reduce<{[key: string]: RuneterraCard}>((obj, {card}) => {
            const {cardCode} = card as unknown as RuneterraCard;
            obj[cardCode] = card as unknown as RuneterraCard;
            return obj;
        }, {});

    return {
        props: {cards: cards},
    };
}

const Home: NextPage<{cards: {[key: string]: RuneterraCard}}> = ({cards}) => {
    return (
        <div>
            <Head>
                <title>Runeterra Deckbuilder</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <CardContext.Provider value={cards}>
                <DeckBuilder />
            </CardContext.Provider>
            <footer>
                <RiotDisclosure />
            </footer>
        </div>
    );
};

export default Home;
