import type {NextPage} from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import {useRouter} from "next/router";

function Header() {
    return (
        <header className={styles.header}>
            <div className={styles.container}>
                <div className={styles.logo}>Runeterra App</div>
                <nav className={styles.nav}>
                    <ul className={styles["nav-list"]}>
                        <li className={styles["nav-list__item"]}>Cards</li>
                        <li className={styles["nav-list__item"]}>Deck Builder</li>
                        <li className={styles["nav-list__item"]}>Decks</li>
                        <li className={styles["nav-list__item"]}>Login / Logout</li>
                    </ul>
                </nav>
            </div>
        </header>
    );
}

const Card: NextPage = ({cards}: any) => {
    const router = useRouter();
    const {id} = router.query;
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <p>{id}</p>
        </div>
    );
};

export default Card;
